### PR TITLE
Resolve bug where iOS 12 has a big black void under the content and above the keyboard

### PR DESCRIPTION
**Pull request by zspencer**
Apply patch from @mattio

Gist: https://gist.github.com/mattio/ba5d77474e725463bc75cfbf1dba0cca
Comment: https://github.com/cjpearson/cordova-plugin-keyboard/issues/77#issuecomment-425554227

### CODE REVIEW

**Comment by zspencer** [comment]
Unfortunately, I'm seeing some odd behavior on iPhone X and XS, where the webview shrinks initially, then expands once the keyboard finishes appearing. @mattio do you have any insights or availability to pair to figure this out?

**Comment by vikseriq** [comment]
Confirming an odd behavior on every iOS12 device related with visible on-resize interface glitch.
Also when switching among fields via build-in keyboard shortcut panel the iOS move WebView and the dark area become visible.
Demonstrating screen recording: https://monosnap.com/file/9zxfdHgctPiEESDntUJfBQV97AYIYP

So – not a solution, @wecohere @zspencer need to investigate more.

**Comment by zspencer** [comment]
@vikseriq yep :/ that's why I wound up dropping this plugin and using ionic-webview and ionic-keyboard per this comment - https://github.com/cjpearson/cordova-plugin-keyboard/issues/77#issuecomment-433467550

**Comment by edvenkat** [comment]
@mattio and @zspencer currently i am using ur branch but i am facing the below issue (refer below link) above 12.0
can you please tell the solution for this?

for your reference
https://camo.githubusercontent.com/e19923ed896d8232238d4714c04243f27f386437/687474703a2f2f692e696d6775722e636f6d2f514458307457512e676966

**Pull request closed without merging**
